resources:
  - name: go_gitRepo_demo
    type: GitRepo
    configuration:
      path: ranjithrs/swampup-go-service
      gitProvider: ranjithr_github

  - name: svc_build_info_demo
    type: BuildInfo
    configuration:
      sourceArtifactory: jfrogtraining
      buildName: svc_build
      buildNumber: 1

  - name: svc_promoted_build_info_demo
    type: BuildInfo
    configuration:
      sourceArtifactory: jfrogtraining
      buildName: svc_build
      buildNumber: 1

  - name: backend_gitRepo_demo
    type: GitRepo
    configuration:
      path: ranjithrs/swampup-java-backend-service
      gitProvider: ranjithr_github

  - name: app_build_info_demo
    type: BuildInfo
    configuration:
      sourceArtifactory: jfrogtraining
      buildName: backend_build
      buildNumber: 1

  - name: app_promoted_build_info_demo
    type: BuildInfo
    configuration:
      sourceArtifactory: jfrogtraining
      buildName: backend_build
      buildNumber: 1

  - name: frontend_gitRepo_demo
    type: GitRepo
    configuration:
      path: ranjithrs/swampup-vue-frontend
      gitProvider: ranjithr_github

  - name: releaseBundle_demo
    type: ReleaseBundle
    configuration:
      sourceDistribution: distribution
      name: demo-app
      version: v2.0.0

  - name: signedBundle_demo
    type: ReleaseBundle
    configuration:
      sourceDistribution: distribution
      name: demo-app
      version: v2.0.0

  - name: distributionRules_demo
    type: DistributionRule
    configuration:
      sourceDistribution: distribution
      serviceName: "*"
      siteName: "*"
      cityName: "*"
      countryCodes:
        - "*"

  - name: deploy_vm_demo
    type: VmCluster
    configuration:
      sshKey: deploy_ssh
      targets:
        - 35.236.12.2

pipelines:
  - name: demo_service_demo
    steps:
      - name: bld_svc_demo
        type: DockerBuild
        configuration:
          nodePool: ranjithr_pool 
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: jfrogtraining-docker-local.jfrog.io/gosvc
          dockerImageTag: $run_number
          inputResources:
            - name: go_gitRepo_demo
          integrations:
            - name: jfrogtraining

      - name: push_svc_demo
        type: DockerPush
        configuration:
          nodePool: ranjithr_pool
          targetRepository: docker-local
          integrations:
            - name: jfrogtraining
          inputSteps:
            - name: bld_svc_demo

      - name: publish_svc_build_demo
        type: PublishBuildInfo
        configuration:
          nodePool: ranjithr_pool
          inputSteps:
            - name: push_svc_demo
          outputResources:
            - name: svc_build_info_demo

      - name: promote_svc_build_demo
        type: PromoteBuild
        configuration:
          nodePool: ranjithr_pool
          targetRepository: pipelines-demo
          integrations:
            - name: jfrogtraining
          inputResources:
            - name: svc_build_info_demo
          outputResources:
            - name: svc_promoted_build_info_demo

  - name: demo_app_pipeline
    steps:
      - name: bld_backend_demo
        type: MvnBuild
        configuration:
          nodePool: ranjithr_pool 
          runtime:
            type: image
            image:
              custom:
                name: drydock/u18java
                tag: master
          sourceLocation: .
          mvnCommand: clean install -ntp
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: backend_gitRepo_demo
          integrations:
            - name: jfrogtraining


      - name: bld_frontend
        type: NpmBuild
        configuration:
          nodePool: ranjithr_pool
          npmArgs: --no-progress --no-audit
          sourceLocation: .
          repositoryName: npm-virtual
          inputResources:
            - name: frontend_gitRepo_demo
          integrations:
            - name: jfrogtraining

      - name: pack_frontend
        type: Bash
        configuration:
          nodePool: ranjithr_pool
          inputSteps:
            - name: bld_frontend
          integrations:
            - name: jfrogtraining
        execution:
          onStart:
            - export tempStateLocation="$step_tmp_dir/npmSourceState"
            - restore_run_files npmBuildInputGitRepo $tempStateLocation
            - pushd $tempStateLocation
            - npm run build
            - add_run_files $tempStateLocation/. npmBuildInputGitRepo

      - name: publish_frontend_demo
        type: NpmPublish
        configuration:
          nodePool: ranjithr_pool
          repositoryName: npm-prod-local
          inputSteps:
            - name: pack_frontend
          integrations:
            - name: jfrogtraining
        execution:
          onStart:
            - export inputNpmBuildStepName="bld_frontend"

      - name: build_app_demo
        type: Bash
        configuration:
          nodePool: ranjithr_pool
          environmentVariables:
            dockerImageName: jfrogtraining-docker-local.jfrog.io/app
            dockerImageTag: ${run_number}
            test: 123
          inputResources:
            - name: backend_gitRepo_demo
          inputSteps:
            - name: bld_backend_demo
            - name: publish_frontend_demo
          integrations:
            - name: jfrogtraining
        execution:
          onExecute:
            - printenv
            - rm -rf $run_dir/workspace/jfrog
            - retry_command jfrog rt config --url $int_jfrogtraining_url --user $int_jfrogtraining_user --apikey $int_jfrogtraining_apikey --interactive=false
            - pushd $res_backend_gitRepo_demo_resourcePath
            - echo $int_jfrogtraining_url
            - echo $run_number
            - echo $dockerImageName
            - echo $dockerImageTag
            - echo $test
            - add_run_variables buildStepName=${step_name}
            - add_run_variables ${step_name}_buildNumber=${run_number}
            - add_run_variables ${step_name}_buildName=${pipeline_name}
            - docker build --pull -t $dockerImageName:$dockerImageTag --build-arg REGISTRY=${int_jfrogtraining_url} .
            - jfrog rt bce $pipeline_name $run_number
            - jfrog rt docker-push jfrogtraining-docker-local.jfrog.io/app:${run_number} docker-local --build-name=$pipeline_name --build-number=$run_number
            - add_run_files /tmp/jfrog/. jfrog

      - name: publish_app_build_demo
        type: PublishBuildInfo
        configuration:
          nodePool: ranjithr_pool
          inputSteps:
            - name: build_app_demo
          outputResources:
            - name: app_build_info_demo

      - name: promote_app_build
        type: PromoteBuild
        configuration:
          nodePool: ranjithr_pool
          targetRepository: pipelines-demo
          integrations:
            - name: jfrogtraining
          inputResources:
            - name: app_build_info_demo
          outputResources:
            - name: app_promoted_build_info_demo

  - name: demo_release_pipeline
    steps:
      - name: bundle
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: demo-app
          releaseBundleVersion: v2.0.$run_number
          dryRun: false
          sign: false
          description: "some random test description"
          inputResources:
            - name: svc_promoted_build_info_demo
              trigger: false
            - name: app_promoted_build_info_demo
              trigger: false
          outputResources:
            - name: releaseBundle_demo

      - name: sign_demo
        type: SignReleaseBundle
        configuration:
          inputResources:
            - name: releaseBundle_demo
          outputResources:
            - name: signedBundle_demo

      - name: distribute
        type: DistributeReleaseBundle
        configuration:
          dryRun: false
          inputResources:
            - name: signedBundle_demo
            - name: distributionRules_demo
          integrations:
            - name: jfrogtraining

      - name: deploy
        type: Bash
        configuration:
          environmentVariables:
            docker_repository: demo
            artifactory_address: 35.227.181.186
          integrations:
            - name: edge_art
          inputResources:
            - name: deploy_vm_demo
            - name: svc_promoted_build_info_demo
              trigger: false
            - name: app_promoted_build_info_demo
              trigger: false
          inputSteps:
            - name: distribute
        execution:
          onExecute:
            - ssh -i ~/.ssh/deploy_vm_demo eladh@${res_deploy_vm_demo_targets_0} sudo /home/eladh/deploy-to-prod-test.sh $artifactory_address $docker_repository $int_edge_art_apikey $res_app_promoted_build_info_demo_buildNumber $res_svc_promoted_build_info_demo_buildNumber
